import { Routes } from '@angular/router';

import { DashboardComponent } from '../../components/dashboard/dashboard.component';
import { UserProfileComponent } from '../../components/user-profile/user-profile.component';
import { AddAlocacaoComponent } from 'app/components/alocacao/add-alocacao/add-alocacao.component';
import { ListarEmpresasComponent } from 'app/components/empresa/listar-empresas/listar-empresas.component';
import { ListarUsuariosComponent } from 'app/components/usuarios/listar-usuarios/listar-usuarios.component';
import { CriarEmpresaComponent } from 'app/components/empresa/criar-empresa/criar-empresa.component';
import { CriarUsuarioComponent } from 'app/components/usuarios/criar-usuario/criar-usuario.component';
import { VisualizarEmpresaComponent } from 'app/components/empresa/visualizar-empresa/visualizar-empresa.component';
import { AddAlocacaoEmpresaComponent } from 'app/components/alocacao/add-alocacao-empresa/add-alocacao-empresa.component';
import { ListarFatoresComponent } from 'app/components/fatores/listar-fatores/listar-fatores.component';
import { AddFatorComponent } from 'app/components/fatores/add-fator/add-fator.component';
import { AddConfiguracaoComponent } from 'app/components/configuracao/add-configuracao/add-configuracao.component';
import { ListarConfiguracoesComponent } from 'app/components/configuracao/listar-configuracoes/listar-configuracoes.component';
import { EditConfiguracaoComponent } from 'app/components/configuracao/edit-configuracao/edit-configuracao.component';
import { ListarMedicoesComponent } from 'app/components/medicao/listar-medicoes/listar-medicoes.component';
import { VerMedicaoComponent } from 'app/components/medicao/ver-medicao/ver-medicao.component';
import { CriarMedicaoComponent } from 'app/components/medicao/criar-medicao/criar-medicao.component';
import { VerMedicaoPessoaComponent } from 'app/components/medicao/ver-medicao-pessoa/ver-medicao-pessoa.component';
import { CriarMedicaoPessoaComponent } from 'app/components/medicao/criar-medicao-pessoa/criar-medicao-pessoa.component';
import { TesteCorsComponent } from 'app/components/teste-cors/teste-cors.component';

export const AdminLayoutRoutes: Routes = [
    { path: 'dashboard',                                        component: DashboardComponent },
    { path: 'user-profile',                                     component: UserProfileComponent },
    { path: 'companies-list',                                   component: ListarEmpresasComponent },
    { path: 'companies-create',                                 component: CriarEmpresaComponent },
    { path: 'company/:id',                                      component: VisualizarEmpresaComponent },
    { path: 'company/:id/add-alocation',                        component: AddAlocacaoEmpresaComponent },
    { path: 'users-list',                                       component: ListarUsuariosComponent },
    { path: 'users-create',                                     component: CriarUsuarioComponent },
    { path: 'user-profile/add-alocation/:id',                   component: AddAlocacaoComponent },
    { path: 'factors-list',                                     component: ListarFatoresComponent },
    { path: 'factors-create',                                   component: AddFatorComponent },
    { path: 'config/company/:id',                               component: AddConfiguracaoComponent },
    { path: 'config/:idConfig/company/:idCompany',              component: EditConfiguracaoComponent },
    { path: 'configs-list',                                     component: ListarConfiguracoesComponent },
    { path: 'measurement-list',                                 component: ListarMedicoesComponent },
    { path: 'measurement/:id',                                  component: VerMedicaoComponent },
    { path: 'measurement-create',                               component: CriarMedicaoComponent },
    { path: 'measurement/:id/person/:measurementPersonId',      component: VerMedicaoPessoaComponent },
    { path: 'measurement/:id/person-create',                    component: CriarMedicaoPessoaComponent },
    { path: 'teste-cors',                    component: TesteCorsComponent },
];
